In [15]:
import numpy as np
import scipy.spatial

In [6]:
b = np.array([1,2,3,4,5], dtype=float)
c = np.array([True, False, True])
f = np.arange(1,2,0.3,dtype=float)
f

array([ 1. ,  1.3,  1.6,  1.9])

In [11]:
a = np.array([6,3,-5])
b = np.array([-1,0,7])

np.linalg.norm(a, ord=2), np.linalg.norm(b, ord=2)

(8.3666002653407556, 7.0710678118654755)

In [19]:
scipy.spatial.distance.cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[ 14.2126704]])

In [28]:
a = np.eye(4, 5)
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [36]:
a[[0,3], [1, 3]]

array([ 0.,  1.])

In [1]:
0.49**2+0.49*0.38+0.38**2+0.1*0.49+0.1**2+0.03*0.49+0.03*0.38+0.03*0.1+0.03**2

0.6597000000000001

In [3]:
0.5*0.2

0.1